"""Shared pytest fixtures + TS-fixture path helpers.

TS SDK fixtures are authoritative — we reuse them directly rather than
copying. The reference canonical-JSON hex is generated by the Go assembler
(see ts/src/verify-certificate/__fixtures__/gen-go-reference.go) and lives
at canonical-json-go-reference.hex; Python + Go SDKs byte-compare against
it for cross-language byte-equality.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

# Python tests directory → monorepo/python/tests → monorepo root.
_MONOREPO_ROOT = Path(__file__).resolve().parent.parent.parent

_TS_FIXTURES = (
    _MONOREPO_ROOT / "ts" / "src" / "verify-certificate" / "__fixtures__"
)


@pytest.fixture(scope="session")
def ts_fixtures_dir() -> Path:
    assert _TS_FIXTURES.is_dir(), (
        f"Expected TS fixtures at {_TS_FIXTURES}. Python tests require the "
        "monorepo layout — run via pytest from within theveil-sdks/python/."
    )
    return _TS_FIXTURES


@pytest.fixture(scope="session")
def witness_keypair(ts_fixtures_dir: Path) -> dict[str, str]:
    """Real Ed25519 test keypair used to sign the valid cert fixtures."""

    # Prefer the canonical `test-witness-keypair.json` when present; fall
    # back to the mirror `witness-keypair.json` which is the historical
    # name. The valid-cert fixtures are signed with the private key here.
    for name in ("test-witness-keypair.json", "witness-keypair.json"):
        p = ts_fixtures_dir / name
        if p.is_file():
            return json.loads(p.read_text())
    pytest.fail("No witness keypair fixture found in TS fixtures dir")


def revive_raw_integers(v: Any) -> Any:
    """Mirror of the TS revive logic for ``$rawInt`` fixture markers.

    Python has native ``int`` so the marker just unwraps — no branded type
    needed. The marker exists in the input JSON because TS requires
    explicit integer wrapping at the canonical-JSON boundary.
    """

    if isinstance(v, list):
        return [revive_raw_integers(x) for x in v]
    if isinstance(v, dict):
        if (
            set(v.keys()) == {"$rawInt"}
            and isinstance(v["$rawInt"], int)
            and not isinstance(v["$rawInt"], bool)
        ):
            return int(v["$rawInt"])
        return {k: revive_raw_integers(val) for k, val in v.items()}
    return v


@pytest.fixture(scope="session")
def canonical_reference(ts_fixtures_dir: Path) -> tuple[dict[str, Any], str]:
    """(revived input dict, expected hex string)."""

    raw_input = json.loads(
        (ts_fixtures_dir / "canonical-json-go-reference-input.json").read_text()
    )
    expected_hex = (
        (ts_fixtures_dir / "canonical-json-go-reference.hex").read_text().strip()
    )
    return revive_raw_integers(raw_input), expected_hex


@pytest.fixture(scope="session")
def cert_valid_anchored(ts_fixtures_dir: Path) -> dict[str, Any]:
    return json.loads((ts_fixtures_dir / "cert-valid-anchored.json").read_text())


@pytest.fixture(scope="session")
def cert_valid_failed(ts_fixtures_dir: Path) -> dict[str, Any]:
    return json.loads((ts_fixtures_dir / "cert-valid-failed.json").read_text())


@pytest.fixture(scope="session")
def cert_valid_pending(ts_fixtures_dir: Path) -> dict[str, Any]:
    return json.loads((ts_fixtures_dir / "cert-valid-pending.json").read_text())


@pytest.fixture(scope="session")
def cert_go_signed_reference(ts_fixtures_dir: Path) -> dict[str, Any]:
    """The cert fixture that's byte-identical to a Go-assembler-produced cert
    — the end-to-end authoritative reference for signable + verify."""

    return json.loads((ts_fixtures_dir / "cert-go-signed-reference.json").read_text())
