"""Canonical-JSON byte-equality tests.

The cross-language byte-equality invariant is the single riskiest area of
the SDK port — a one-byte divergence silently produces ``invalid_signature``
on valid certs. The golden fixture (generated by the Go assembler) is the
tripwire; do not skip or soft-fail this module.
"""

from __future__ import annotations

from typing import Any

import pytest

from theveil.verify_certificate import canonical_json


def test_sorts_keys_alphabetically_at_top_level() -> None:
    out = canonical_json({"b": "x", "a": "y"})
    assert out == b'{"a":"y","b":"x"}'


def test_sorts_keys_recursively_in_nested_maps() -> None:
    out = canonical_json({"z": {"y": "b", "x": "a"}, "a": "c"})
    assert out == b'{"a":"c","z":{"x":"a","y":"b"}}'


def test_preserves_array_order() -> None:
    out = canonical_json({"list": ["c", "a", "b"]})
    assert out == b'{"list":["c","a","b"]}'


def test_emits_int_leaves_as_unquoted_json_integers() -> None:
    out = canonical_json({"n": 1, "s": "1"})
    assert out == b'{"n":1,"s":"1"}'


def test_rejects_floats_at_boundary() -> None:
    with pytest.raises(TypeError, match="float"):
        canonical_json({"n": 1.5})


def test_bool_before_int_in_dispatch() -> None:
    # bool subclasses int in Python; True/False must emit as true/false,
    # never as 1/0.
    out = canonical_json({"a": True, "b": False})
    assert out == b'{"a":true,"b":false}'


def test_escapes_html_chars_and_line_separators_in_lowercase_hex() -> None:
    out = canonical_json({"k": "<>&\u2028\u2029"})
    # Go emits: {"k":"\u003c\u003e\u0026\u2028\u2029"}
    assert out == b'{"k":"\\u003c\\u003e\\u0026\\u2028\\u2029"}'


def test_does_not_double_escape_quotes_or_backslashes() -> None:
    out = canonical_json({"k": '"\\'})
    assert out == b'{"k":"\\"\\\\"}'


def test_canonicalizes_sample_veil_shaped_map_byte_for_byte() -> None:
    out = canonical_json(
        {
            "certificate_id": "veil_abc",
            "request_id": "req_123",
            "protocol_version": 2,
            "claim_ids": ["clm_1", "clm_2"],
            "issued_at": "2026-04-20T05:24:12.710321721Z",
            "_integer_probe": 1,
            "witness_key_id": "witness_v1",
        }
    )
    assert out == (
        b'{"_integer_probe":1,"certificate_id":"veil_abc",'
        b'"claim_ids":["clm_1","clm_2"],'
        b'"issued_at":"2026-04-20T05:24:12.710321721Z",'
        b'"protocol_version":2,"request_id":"req_123","witness_key_id":"witness_v1"}'
    )


def test_handles_empty_maps_and_arrays() -> None:
    assert canonical_json({}) == b"{}"
    assert canonical_json({"a": []}) == b'{"a":[]}'


def test_rejects_circular_references_in_objects() -> None:
    cyclic: dict[str, Any] = {}
    cyclic["self"] = cyclic
    with pytest.raises(TypeError, match="circular"):
        canonical_json(cyclic)


def test_rejects_circular_references_in_arrays() -> None:
    arr: list[Any] = []
    arr.append(arr)
    with pytest.raises(TypeError, match="circular"):
        canonical_json({"a": arr})


def test_rejects_bytes() -> None:
    with pytest.raises(TypeError, match="bytes"):
        canonical_json({"a": b"payload"})


def test_rejects_non_str_dict_keys() -> None:
    with pytest.raises(TypeError, match="dict key"):
        canonical_json({1: "x"})


def test_rejects_unsupported_types() -> None:
    with pytest.raises(TypeError, match="unsupported"):
        canonical_json({"a": object()})


def test_matches_go_reference_hex_byte_for_byte(
    canonical_reference: tuple[dict[str, Any], str],
) -> None:
    """Golden cross-check against Go assembler reference output.

    The hex bytes in canonical-json-go-reference.hex are the raw output of
    dual-sandbox-architecture/pkg/veil/canonical.go run on the same input
    (with ``$rawInt`` markers revived as native ints). This is the
    authoritative faithfulness assertion — without it, the Python port
    proves only self-consistency.
    """

    revived, expected_hex = canonical_reference
    out = canonical_json(revived)
    assert out.hex() == expected_hex
